# Generated by Django 5.2.9 on 2025-12-23 16:28

from django.db import migrations

import django_pgviews.db.migrations.operations


class Migration(migrations.Migration):
    dependencies = [
        ("schemadbtest", "0001_initial"),
    ]

    operations = [
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="SchemaMonthlyObservationMaterializedView",
            materialized=True,
            db_name="schemadbtest_schemamonthlyobservationmaterializedview",
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="SchemaMonthlyObservationView",
            materialized=False,
            db_name="schemadbtest_schemamonthlyobservationview",
        ),
    ]
