# Generated by Django 5.2.9 on 2025-12-23 16:30

from django.db import migrations

import django_pgviews.db.migrations.operations


class Migration(migrations.Migration):
    dependencies = [
        ("multidbtest", "0001_initial"),
    ]

    operations = [
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="MonthlyObservation",
            materialized=True,
            db_name="multidbtest_monthlyobservation",
        ),
    ]
