# Generated by Django 5.2.9 on 2025-12-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomSchemaMaterializedRelatedViewWithIndex",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "db_table": "test_schema.my_custom_view_with_index",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomSchemaView",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "db_table": "test_schema.my_custom_view",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DependantMaterializedView",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DependantView",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LatestSuperusers",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MaterializedRelatedView",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MaterializedRelatedViewWithIndex",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MaterializedRelatedViewWithNoData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MaterializedRelatedViewWithReallyReallyReallyReallyReallyReallyLongName",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RelatedView",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SimpleUser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Superusers",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TestModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
