# Generated by Django 5.2.9 on 2025-12-23 16:28

from django.db import migrations

import django_pgviews.db.migrations.operations


class Migration(migrations.Migration):
    dependencies = [
        ("viewtest", "0001_initial"),
    ]

    operations = [
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="DependantMaterializedView",
            materialized=True,
            db_name="viewtest_dependantmaterializedview",
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="SimpleUser",
            materialized=False,
            db_name="viewtest_simpleuser",
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="Superusers",
            materialized=False,
            db_name="viewtest_superusers",
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="CustomSchemaView",
            materialized=False,
            db_name="test_schema.my_custom_view",
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="MaterializedRelatedViewWithReallyReallyReallyReallyReallyReallyLongName",
            materialized=True,
            db_name="viewtest_materializedrelatedviewwithreallyreallyreallyreallca1d",
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="LatestSuperusers",
            materialized=False,
            db_name="viewtest_latestsuperusers",
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="DependantView",
            materialized=False,
            db_name="viewtest_dependantview",
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="MaterializedRelatedView",
            materialized=True,
            db_name="viewtest_materializedrelatedview",
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="MaterializedRelatedViewWithNoData",
            materialized=True,
            db_name="viewtest_materializedrelatedviewwithnodata",
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="MaterializedRelatedViewWithIndex",
            materialized=True,
            db_name="viewtest_materializedrelatedviewwithindex",
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="CustomSchemaMaterializedRelatedViewWithIndex",
            materialized=True,
            db_name="test_schema.my_custom_view_with_index",
        ),
        django_pgviews.db.migrations.operations.RegisterViewOperation(
            name="RelatedView",
            materialized=False,
            db_name="viewtest_relatedview",
        ),
    ]
